### ISSUE TITLE
Custom list placeholder view?

### ISSUE THREAD

**Issue by Daltron** [malkouz/ListPlaceholder#1]
Hi @malkouz! 😄 This looks promising but the ability to not be able to define a custom view as the placeholder is an absolute deal breaker for me. Do you plan to support this functionality in the future?

**Comment by malkouz** [comment]
Hello @Daltron, Thank you for your contribution.

The placeholder is now supported for custom view.

**Comment by Daltron** [comment]
@malkouz Awesome! However, an example in the README showing exactly how to use a custom view might be nice. The example right now doesn't really show how to create a custom placeholder. What do I inherit from? Do I make it part of the table/collection view? etc.. Further documentation would be great! 😄

**Comment by malkouz** [comment]
For custom placeholder, you need just build it via IB then connect it with IBOutlet
and just call showLoader() method.

once you want to hide placeholder call method hideLoader() then hide your view or remove it from superView

Regards
