### ISSUE TITLE
Views inside StackView not working properly

### ISSUE THREAD

**Issue by Muhammad-AhmadRafique** [malkouz/ListPlaceholder#12]
Hi Everyone, I am using this amazing library, it is working fine.
But It is not working for stackViews in tableView or collectionView, it consider all the subviews in the stackView as a single View and highlight the whole stackView.

Does anyone have any idea to resolve this issue ?

**Comment by bigearsenal** [comment]
Feel like the author is not active at this moment. I created a Pull Request but noone has answered. #22 
So you can try my solution
`pod 'ListPlaceholder', :git => "https://github.com/bigearsenal/ListPlaceholder.git"`

**Comment by bigearsenal** [comment]
Fixed by pull request #22
