### ISSUE TITLE
How to Show this effect on  Empty table View

### ISSUE THREAD

**Issue by mayankwadhwa111** [malkouz/ListPlaceholder#13]
Hi Malkouz your library is much appreciated . 

I want to display the placeholders on the screen while in the background api is being called i have already checked a similar question in the issues section but have not found any leads as i am new ;) .

My tableView populates when the API has done fetching data from it 
How can i show placeholders before populating that please?

**Comment by mayankwadhwa111** [comment]
Working very fine i followed it carefully and BAm

**Comment by NirajCapermint** [comment]
@mayankwadhwa111 Can you share how it worked for you, I am facing the same issue.
