### ISSUE TITLE
Show Placeholder while App is fetching data from API

### ISSUE THREAD

**Issue by toseefkhilji** [malkouz/ListPlaceholder#4]
Hi @malkouz ,

Great Library !!

But,

I want show placeholder while app is getting data from API, 
My datasource **Array** is initialize after parsing data, and meanwhile I need to show placeholder.

So When datasource Array is empty this is not working.

**Comment by malkouz** [comment]
hello @toseefkhilji ,

Thank you for your contribution, I hope below code will help you:

    var list = [Model]()
    var isNowLoading = false

    func fetchData(){
        isNowLoading = true
        tableView.showLoader()
        tableView.reloadData()
        
        //Start load data from api..
        // ..
        // ..
        // add models to your list
        //the on completion
        self.tableView.hideLoader()
        tableView.reloadData()
        isNowLoading = false
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if isNowLoading {
            return 5 //as example
        }
        return list.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell", for: indexPath)
        
        if isNowLoading{
            //do nothing
        }else{
            let model = list[indexPath.row]
            //start configure cell content
            //..
        }
        
        return cell
    }

**Comment by toseefkhilji** [comment]
Hi @malkouz ,

Yes, I'm already doing this.

I thought, If there is some other way of doing this.

Thanks.

**Comment by malkouz** [comment]
this is the way to make placeholder same of your cell.

you can make custom view placeholder if you want to make customized placeholder.
check example please

**Comment by Ornolfr** [comment]
@malkouz What is the best way to determine the max cell count that can be on screen in order to put it here?
```
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    if isNowLoading {
        return X // put here
    }
    return list.count
}
```
